### ISSUE TITLE
Create Staging and Prod VMs

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_api#10]
- [ ] Staging VM
- [ ] Prod VM

**Comment by maxkadel** [comment]
Questions:
- how many VMs for each environment? 
- how much CPU/memory/storage? 
- what to name them (allsearch_prod1? allsearch_rails_prod1?)?

**Comment by acozine** [comment]
URIs: allsearch-api.princeton.edu and allsearch-api-staging.princeton.edu

**Comment by sandbergja** [comment]
@acozine thanks for the shiny new VMs!  Can we close this ticket?

**Comment by acozine** [comment]
@sandbergja if you are okay with just a single staging server for now, we can close this. If you'd like to get a second server, we can either leave this open or close this and file another more specific ticket for that work. It may be a while before I can juggle things around in the staging env to get you another box there.

**Comment by kevinreiss** [comment]
Ok, we will create a new ticket for a second staging server. Having that for this project isn't urgent right now, but long-term it would be good to have two boxes.
