### ISSUE TITLE
Match database search result order to  LibGuides AZ database search

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/allsearch_api#108]
### User story
When I use the AllSearch and choose to go to the original search service, it would be confusing to see a different search result.

### Acceptance criteria
Searching against the `database` endpoint in the allsearch_api consistently gives the same result order as the LibGuides AZ database search - see https://libguides.princeton.edu/az.php

### Concrete example
- Search `oxford music` in both, you will see a different order of results

### Implementation notes, if any
- May want to change the weight of different fields, see [weighted migration](https://github.com/pulibrary/allsearch_api/blob/ab60f02ed621db8785444aca411221924c60c6ae/db/migrate/20230921193904_add_weights_to_searchable.rb#L5-L11). 
 

This ticket was broken out from #33. @VickieKarasic  is checking in with vendor to see if we can find out more about their search weighting.

**Comment by VickieKarasic** [comment]
Springshare's response: 

Both the A-Z Databases search and the LibGuides Search page results are determined by term relevancy with each field given equal weight. 

- For A-Z database searches, these are the fields that are present when adding or editing a database:
description, keywords, librarian note, more info, name, slug/friendly URL, subjects, URL, and vendor name

- The more times the search term(s) appear in these fields, the higher it will be ranked in the search results.

So it may be that "Oxford Scholarship Online: Music" has more mentions of Oxford and/or Music in its description, keywords, etc. than "Oxford Music" does and thus is shown higher on the results list.

**Comment by kevinreiss** [comment]
Moved this to backlog since it seems like based on Vickie's investigation this isn't possible at this point: see https://github.com/pulibrary/allsearch_api/issues/33.

**Comment by kevinreiss** [comment]
It seems like per @VickieKarasic's comment we can't really do much here.

**Comment by beth-german** [comment]
@kevinreiss will write new ticket that reflects feasible solution, this ticket will be closed.
