### ISSUE TITLE
Catalog endpoint: include electronic resource URLs in the API output

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/allsearch_api#125]
### User story

As a developer, I would like to have access to URLs of catalog electronic resources, so that I can display them in the client application.

The `electronic_portfolio_s` field should be used if present and we can use the 856 `electronic_access_1display` field as a fallback value. There should only be one field displayed.

### Acceptance criteria

- [ ] When my search includes an electronic access title, the URL is included in the API results in a new key value pair (maybe "resource_url")
- [ ] The url key-value pair should remain as it is (i.e. it should be a URL to the catalog record).

### Concrete example

https://allsearch-api.princeton.edu/search/catalog?query=%20Didgeridoo-Mania -- all three results should have a link to the electronic access.

**Comment by kevinreiss** [comment]
There are also "legacy" 856 fields that also should be treated as online content. that content will be found in ```electronic_access_1display```
