### ISSUE TITLE
Swagger file does not conform to OpenAPI standard

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/allsearch_api#167]
### Expected behavior

The following does not produce errors:
```
brew install daveshanley/vacuum/vacuum
vacuum lint -d -e swagger/**/*.yaml
```

### Actual behavior
It has several errors:
* Info section is missing a description: `description` must be set
* Server URL is not valid: must not have a trailing slash
* the 'get' operation at path [path] does not contain an operationId 
* Path must not include query string

### Steps to replicate

```
brew install daveshanley/vacuum/vacuum
vacuum lint -d -e swagger/**/*.yaml
```

### Impact of this bug

We can't use certain automated tools, for example [schemathesis](https://github.com/schemathesis/schemathesis), unless the swagger file conforms to this standard.

### Success criteria

- [ ] `vacuum lint -d -e swagger/**/*.yaml` succeeds
- [ ] CI runs `vacuum lint -d -e swagger/**/*.yaml` to catch future issues

**Comment by sandbergja** [comment]
Thanks for correcting the record, @Stranger6667, and for your offer to help !  Yeah, it seems that #168 didn't change the situation for me as far as running schemathesis.

* The following works fine: `st run --checks all swagger/v1/swagger.yaml --base-url https://allsearch-api.princeton.edu`.
* But when I try to run `st run --checks all https://allsearch-api.princeton.edu/api-docs/v1/swagger.yaml` (which should be the identical swagger.yaml file), I get:

```
Schema Loading Error

Received unsupported content while expecting a JSON or YAML payload for Open API

Tip: Verify that the URL points directly to the Open API schema
```

So it seems that there is something happening with either how schemathesis fetches the yaml file, or how we serve it?

**Comment by Stranger6667** [comment]
Thank you for sharing the command!

The underlying error comes from the YAML parser:

```
unacceptable character #x0080: control characters are not allowed
  in "<unicode string>", position 758
```

It is here - `Theophile-Alexandre Steinlen, 1859\xe2\x80\x931923;`. It is raw content received from the network

I am going to adjust the error messages so it is easier to observe the underlying issue
