### ISSUE TITLE
Postgres errors on oauth_tokens table

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/allsearch_api#184]
### Expected behavior
Normal Postgres actions do not raise errors

### Actual behavior
- Generating many errors on lib-postgres-prod1, can be [viewed in Datadog](https://app.datadoghq.com/logs?query=status%3Aerror%20-service%3Anginxplus%20%40statement%3A%22INSERT%20INTO%20%5C%22oauth_tokens%5C%22%20%28%5C%22service%5C%22%2C%20%5C%22endpoint%5C%22%2C%20%5C%22token%5C%22%2C%20%5C%22expiration_time%5C%22%2C%20%5C%22created_at%5C%22%2C%20%5C%22updated_at%5C%22%29%20VALUES%20%28%241%2C%20%242%2C%20%243%2C%20%244%2C%20%245%2C%20%246%29%20RETURNING%20%5C%22id%5C%22%22&agg_m=count&agg_t=count&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&source=monitor_notif&stream_sort=desc&viz=stream&from_ts=1706708986457&to_ts=1707313786457&live=true)
- Main error is `duplicate key value violates unique constraint "index_oauth_tokens_on_service"`, detail is `Key (service)=(libguides) already exists.` - also has examples for libanswers.
Example log:
```json
{
	"id": "AgAAAY2DztoGKd2TTwAAAAAAAAAYAAAAAEFZMkR6dHl0QUFCOTludEtKbGxOZlFBRAAAACQAAAAAMDE4ZDgzZDItNTU2ZS00MmI3LTg0N2EtOTc5ZDc4ODAwMWVj",
	"content": {
		"timestamp": "2024-02-07T13:43:08.038Z",
		"tags": [
			"filename:pg.json",
			"env:prod",
			"service:postgres_cluster",
			"sourcecategory:database",
			"postgresql",
			"role:postgresql",
			"source:postgresql",
			"datadog.submission_auth:private_api_key",
			"dbm:true",
			"dbms:postgres",
			"port:5432",
			"server:localhost"
		],
		"host": "lib-postgres-prod1",
		"service": "postgres_cluster",
		"message": "duplicate key value violates unique constraint \"index_oauth_tokens_on_service\"",
		"attributes": {
			"error_severity": "ERROR",
			"backend_type": "client backend",
			"ps": "INSERT",
			"query_id": 4446278591458940400,
			"line_num": 43,
			"remote_port": 45436,
			"session_id": "65c388d5.461f5",
			"txid": 144363235,
			"pid": 287221,
			"vxid": "81/855977",
			"session_start": "2024-02-07 13:42:45 UTC",
			"remote_host": "128.112.204.108",
			"application_name": "Passenger AppPreloader: /opt/allsearch_api/current",
			"dbname": "allsearch_api_prod",
			"statement": "INSERT INTO \"oauth_tokens\" (\"service\", \"endpoint\", \"token\", \"expiration_time\", \"created_at\", \"updated_at\") VALUES ($1, $2, $3, $4, $5, $6) RETURNING \"id\"",
			"detail": "Key (service)=(libguides) already exists.",
			"state_code": "23505",
			"user": "allsearch_api_prod",
			"timestamp": "2024-02-07 13:43:07.520 UTC"
		}
	}
}
```

### Impact of this bug
- Excessive Postgres errors in Datadog, creates noise in logs

**Comment by kevinreiss** [comment]
Just noting that this error pretty much is continuously happening.
