### ISSUE TITLE
CORS policy blocking pulmap on staging 

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/allsearch_api#223]
### Expected behavior
allsearch-staging should be able to get data for all services from allsearch-api-staging

### Actual behavior
CORS policy blocks the pulmap service (and only the pulmap service) on allsearch-staging. GET requests for all other services was successful.

```
Access to XMLHttpRequest at 'https://allsearch-api-staging.princeton.edu/search/pulmap?query=indiana' from origin 'https://allsearch-staging.princeton.edu' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

XHR failed loading: GET "https://allsearch-api-staging.princeton.edu/search/pulmap?query=indiana".

GET https://allsearch-api-staging.princeton.edu/search/pulmap?query=indiana net::ERR_FAILED 500 (Internal Server Error)
```

### Steps to replicate
- On VPN, go to [allsearch-staging.princeton.edu](https://allsearch-staging.princeton.edu/)
- Do a search
- Check the console (on Chrome, right-click, select "inspect", click on "console" tab), you will see failures for pulmap

### Impact of this bug
Cannot check pulmap behavior on staging

### Implementation notes, if any
- Tests in [spec/requests/cors_spec.rb](https://github.com/pulibrary/allsearch_api/blob/main/spec/requests/cors_spec.rb)
- Check the [cors initializer](https://github.com/pulibrary/allsearch_api/blob/main/config/initializers/cors.rb), especially the regex.

**Comment by sandbergja** [comment]
I think that in this case, the CORS is a misleading message from the browser, I'm seeing in the network tab that the maps is giving a 500 response.  And the 500 response doesn't have the CORS header, which I think triggers the browser message, but the fundamental problem is that it's a 500.
