### ISSUE TITLE
BestBet, Database, and Staff get an ArgumentError if you search for 0%000

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/allsearch_api#245]
### Expected behavior
These don't throw an error:
* https://allsearch-api.princeton.edu/search/best-bet?query=0%000
* https://allsearch-api.princeton.edu/search/database?query=0%000
* https://allsearch-api.princeton.edu/search/staff?query=0%000

### Actual behavior
They do throw a `ArgumentError` error

### Steps to replicate

```
curl "https://allsearch-api.princeton.edu/search/best-bet?query=0%000"
curl "https://allsearch-api.princeton.edu/search/database?query=0%000"
curl "https://allsearch-api.princeton.edu/search/staff?query=0%000"
```

### Impact of this bug

Probably pretty low, but it is unexpected/undefined behavior. And it means that there is a gap in our swagger documentation.

### Honeybadger links

* [staff honeybadger](https://app.honeybadger.io/projects/114176/faults/109321392)
* [databases honeybadger](https://app.honeybadger.io/projects/114176/faults/109321390)
* [best bet honeybadger](https://app.honeybadger.io/projects/114176/faults/109321319)

### Note

I found this with schemathesis. To try it locally from your allsearch_api directory:

```
brew install schemathesis
schemathesis run swagger/v1/swagger.yaml --base-url="https://allsearch-api.princeton.edu/"
```

**Comment by rladdusaw** [comment]
I think you can fix this with the rescue_uri_error method I created in https://github.com/pulibrary/allsearch_api/pull/241
