### ISSUE TITLE
Go live banner - display on 07/22/2024

### ISSUE THREAD

**Issue by christinach** [pulibrary/allsearch_api#259]
### Desired display
Ask @beth-german about the content of the go live banner. 

### Acceptance criteria

- [x] The banner displays: 
      **All-Search Updated**
       Introducing our new and improved All-Search, upgraded with advanced technology and designed based on your feedback to enhance your research experience. Share your experience and help us improve it further by completing this [brief survey](https://princetonsurvey.az1.qualtrics.com/jfe/form/SV_9oRWjunZdqvepVQ). 

- [x] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [ ] ...

### Notes
- The survey isn't created yet but I believe this link will still be the correct link once the survey is updated.

**Comment by sandbergja** [comment]
Done!

**Comment by beth-german** [comment]
The survey on All-Search is currently going to the staff survey. The one linked in the ticket is the correct survey.

**Comment by sandbergja** [comment]
Thanks for catching that, @beth-german  -- Link updated.
