### ISSUE TITLE
The Databases health check is returning OK when the application can not connect to the database

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/allsearch_api#273]
### Expected behavior
When the Allsearch API can not connect to the database the health check should return an error

### Actual behavior
When the Allsearch API can not connect to the database the health check is returning OK

### Steps to replicate
Edit the database config to prevent the application from connecting to the database
curl localhost/health.json

### Impact of this bug
We will not be alerted if there is an issue with the database, and the load balancer will still send traffic to a server that isn't working correctly.

**Comment by maxkadel** [comment]
You have to re-start the server for it to pick up new database configuration. When you re-start the server after adding a broken config and curl localhost/health.json, I get

```json
{
status: 500,
error: "Internal Server Error"
}
```

If I "pause" the database using Docker desktop, the health page just hangs and does not return anything, which I assume NGINX will see as a failure if it doesn't get a response within a certain time period.
