### ISSUE TITLE
Task to Regularly Load Library Best Bet Content

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_api#37]
Create a task that regularly loads library database content from Springshare (via Lib-jobs) into the index defined in #36. 

- [x] Create a task that loads library best bet content into index
- [x] Schedule task to be run once an hour on production.  This should only run on one of the production boxes at a time.

**Comment by maxkadel** [comment]
Accidentally set to daily, ticket asks for hourly, putting back in progress.
