### ISSUE TITLE
Document Best Bet Add/Update/Delete Workflow

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_api#38]
### User story
As a public services Librarian I want to keep Best Bet content up to date and add or remove Best Bets as needed. 

### Acceptance criteria
- [x] Add the documentation in confluence under 'IT Documentation'
- [x] Set google doc permissions for editors AUX, Web content team, Carol H.
- [x] Create Documentation page for how to maintain the best bets content
- [ ] There is a link to that documentation from the github repo

### Implementation notes, if any
Stakeholders are Jen Hunter and Carol Houghton and others they designate. 
Spreadsheet is at: https://docs.google.com/spreadsheets/d/1UJehce_Bcamist3Y5V80LvhfWVbrMvQtxaIy_jGQjks/edit?gid=170493948#gid=170493948

**Comment by beth-german** [comment]
Link for documentation: https://pul-confluence.atlassian.net/wiki/spaces/IT/pages/104300604/All-Search+Best+Bets

**Comment by kevinreiss** [comment]
I added the editors we discussed to the permissions tab for the google spreadsheet.
