### ISSUE TITLE
Add Articles (Summon) Service to the API

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_api#40]
## Description
Summon is a index of Article content the Library subscribes that Ex Libris maintains and provides via an API. It is labeled "Articles+} on the website. 

### Source Service End User URL
https://princeton.summon.serialssolutions.com/#!/

### Supporting Service Documentation
https://developers.exlibrisgroup.com/summon/apis/
https://github.com/summon/summon.rb (Gem for the API)

### Connectivity
Need Client ID and Secret Key. In last pass as the Summon Over Alma key. See https://github.com/pulibrary/discoveryutils/blob/main/classes/Summon/Summon.php#L275 for the current authentication implementation. 

### Acceptance Criteria

- [x] Returns the results to the equivalent of  a basic keyword query of the service
- [x] Provides Search results with the same default sort as the native service
  interface 
- [x] API response should include a count of the total results
- [x] API response should include a link to the user interface for the source service, so that a user can continue their search there
- [x] API response should include the first 3 results from the source
  application
- [x] API response should include the following fields
    * Title Field
    * Individual URL for each result returned
    * Format
    * Abstract
    * Publication Title
    * Publication Date
    * Publication Year
    * Snippet (highlighted query results)
    * ISxN
    * Full Text Available
  

### Implementation Notes
Current JSON Response: https://library.princeton.edu/utils/articles/any?query=cats&sid=library-main-summon
Current implemetation: https://github.com/pulibrary/discoveryutils/tree/main/classes/Summon
Current "holdings" value is irrelevant

**Comment by kevinreiss** [comment]
[discoveryutils.summon.php_output.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamZFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--21cd3dca26359e060779066fa94705a487a975e5/discoveryutils.summon.php_output.txt)

PHP Object for the query string we currently send in production to the Summon API.

**Comment by kevinreiss** [comment]
support ticket submitted to EXL 9/25.

**Comment by rladdusaw** [comment]
Submitted a ticket to ExLibris and they have responded saying they have forwarded it to their development team and we are waiting for a response from them.

**Comment by rladdusaw** [comment]
The response to our ticket was to use api.summon.serialssolutions.com as the url for the request.
