### ISSUE TITLE
Add a CORS policy that allows GET requests from allsearch.princeton.edu

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/allsearch_api#43]
- [ ] Browsers at allsearch.princeton.edu can make GET fetch requests to allsearch-api.princeton.edu.
- [ ] Browsers at allsearch-staging.princeton.edu can make GET fetch requests to allsearch-api-staging.princeton.edu.
- [ ] The CORS policy doesn't allow other cross-origin requests

This is [#8 in the OWASP API top 10](https://owasp.org/API-Security/editions/2023/en/0xa8-security-misconfiguration/).

**Comment by christinach** [comment]
see also : https://stackoverflow.com/questions/28476643/default-nginx-client-max-body-size
