### ISSUE TITLE
Check for SSRF vulnerabilities

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/allsearch_api#44]
- [ ] Use [this testing procedure](https://owasp.org/www-project-web-security-testing-guide/stable/4-Web_Application_Security_Testing/07-Input_Validation_Testing/19-Testing_for_Server-Side_Request_Forgery) for SSRF vulnerabilities

This is [#7 in the OWASP API top 10](https://owasp.org/API-Security/editions/2023/en/0xa7-server-side-request-forgery/).

**Comment by rladdusaw** [comment]
Recommended fixes in #111
