### ISSUE TITLE
Rename repo to allsearch_api

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/allsearch_api#74]
- Consistent with hostname
- Doesn't lock us into a specific implementation
- 

Update:

- [x] capistrano deploy directory in this repo
- [x] capistrano deploy directory / passenger config in princeton_ansible (see https://github.com/pulibrary/princeton_ansible/pull/4311)
- [x] the name of this repo in github
- [x] let the team know when this has been done, so we can update our git remotes accordingly
- [x] the option in ansible tower (go to the survey tab on the template)
- [x] Link in the MAIN_INFO

**Comment by kevinreiss** [comment]
I think this makes sense.

**Comment by christinach** [comment]
completed
