### ISSUE TITLE
Root of application should give a 200

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/allsearch_api#77]
It's expected for testing, uptime alerts, etc., that there be *something* at the application root. Right now it gives a 404, because there's nothing at the root of the application.

The root of the application should:

- [x] Be in JSON format
- [x] Include "Princeton University Library All Search API"
- [x] Include the mode the software is running in (i.e. dev, staging, prod)
- [x] Include a link to github project
- [x] Include a link to documentation, if it has been merged.  Otherwise, open a new ticket to add this link. [new ticket #91]

**Comment by kevinreiss** [comment]
I think we should return some basic metadata about the project something like

Princeton University Library All Search API
Mode the software is running in (i.e. dev, staging, prod)
Link to github project
Link to documentation 

Should this be returned as HTML or JSON?
