### ISSUE TITLE
Populate Solr fixtures for development

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/allsearch_api#78]
When I bring up my development environment, there should be some searches that result in responses for each service, to check changes to the API.

- [ ] Each service has 5 documents that match the term "cats"

**Comment by sandbergja** [comment]
Take a look at these from pulfalight:

- [refresh_aspace_fixtures](https://github.com/pulibrary/pulfalight/#adding-new-eads-to-test-suite)
- [interesting EADs](https://github.com/pulibrary/pulfalight/#index-interesting-eads)
- [index a specific EAD](https://github.com/pulibrary/pulfalight/#index-a-specific-ead)
