### ISSUE TITLE
Remove CodeQL. 

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/allsearch_api#82]
Codeql runs on github actions, where we only have 20 runners available to our organization.  When there is activity in the princeton_ansible repo, it can take some time before a runner is available.  So all the other checks finish in a minute or so, but we have to wait for codeql.

We already have semgrep and brakeman checks, which run in CircleCI rather than Github Actions, so they aren't affected.  Are these sufficient for our needs?

**Comment by kevinreiss** [comment]
We agreed to disable CodeQL.
